version: "3.3"

services:
  app:
    image: "node:14-slim"
    container_name: docker-nest-js
    build:
      context: .
      dockerfile: Dockerfile
    user: "node"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
      - VERSION=1.0
    volumes:
      - .:/usr/src/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    tty: true
    command: "npm start"
